source "http://rubygems.org"

gem "rails", "3.0.7"
gem "mysql"

gem "authlogic"

gem "disguise"
gem "bcrypt-ruby", :require => "bcrypt"
gem "overlord"
gem "jammit"

gem "muck-engine", :path => "~/projects/muck-engine"
gem "muck-users", :path => "~/projects/muck-users"
gem "muck-shares", :path => "~/projects/muck-shares"
gem 'muck-solr', :require => 'acts_as_solr', :path => "~/projects/acts_as_solr"
gem "muck-contents", :path => "~/projects/muck-contents"
gem 'muck-comments', :path => "~/projects/muck-comments"
gem 'muck-activities', :path => "~/projects/muck-activities"
gem "muck-profiles", :path => "../"

if RUBY_VERSION < "1.9"
  gem "ruby-debug"
end

group :test, :development do
  gem "rspec-rails", ">=2.1.0"
  gem "cucumber-rails"
end

group :test do
  gem "capybara", ">= 0.3.9"
  gem "shoulda"
  gem "factory_girl"
  gem "cucumber"
  gem "rcov"
  gem "rspec", ">=2.1.0"
  gem "database_cleaner"
  gem "spork"
  gem "launchy"
end