# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{muck-profiles}
  s.version = "3.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin Ball", "Joel Duffin"]
  s.date = %q{2010-11-18}
  s.description = %q{Profile engine for the muck system.}
  s.email = %q{justin@tatemae.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "app/controllers/admin/muck/profiles_controller.rb",
    "app/controllers/muck/profiles_controller.rb",
    "app/helpers/muck_profiles_helper.rb",
    "app/views/admin/profiles/edit.html.erb",
    "app/views/profiles/_form.erb",
    "app/views/profiles/_location_suggestion.erb",
    "app/views/profiles/_profile.erb",
    "app/views/profiles/_profile_icon.erb",
    "app/views/profiles/edit.erb",
    "app/views/profiles/index.html.erb",
    "app/views/profiles/show.html.erb",
    "config/locales/ar.yml",
    "config/locales/bg.yml",
    "config/locales/ca.yml",
    "config/locales/cs.yml",
    "config/locales/da.yml",
    "config/locales/de.yml",
    "config/locales/el.yml",
    "config/locales/en.yml",
    "config/locales/es.yml",
    "config/locales/et.yml",
    "config/locales/fa.yml",
    "config/locales/fi.yml",
    "config/locales/fr.yml",
    "config/locales/gl.yml",
    "config/locales/hi.yml",
    "config/locales/hr.yml",
    "config/locales/hu.yml",
    "config/locales/id.yml",
    "config/locales/it.yml",
    "config/locales/iw.yml",
    "config/locales/ja.yml",
    "config/locales/ko.yml",
    "config/locales/lt.yml",
    "config/locales/lv.yml",
    "config/locales/mt.yml",
    "config/locales/nl.yml",
    "config/locales/no.yml",
    "config/locales/pl.yml",
    "config/locales/pt-PT.yml",
    "config/locales/pt.yml",
    "config/locales/ro.yml",
    "config/locales/ru.yml",
    "config/locales/sk.yml",
    "config/locales/sl.yml",
    "config/locales/sq.yml",
    "config/locales/sr.yml",
    "config/locales/sv.yml",
    "config/locales/th.yml",
    "config/locales/tl.yml",
    "config/locales/tr.yml",
    "config/locales/uk.yml",
    "config/locales/vi.yml",
    "config/locales/zh-CN.yml",
    "config/locales/zh-TW.yml",
    "config/locales/zh.yml",
    "config/routes.rb",
    "db/migrate/20090512013727_create_profiles.rb",
    "db/migrate/20091124203137_add_location_to_profiles.rb",
    "db/migrate/20091124205819_add_fields_to_profiles.rb",
    "db/migrate/20100206000906_remove_name_fields.rb",
    "lib/muck-profiles.rb",
    "lib/muck-profiles/config.rb",
    "lib/muck-profiles/engine.rb",
    "lib/muck-profiles/models/profile.rb",
    "lib/muck-profiles/models/user.rb",
    "lib/tasks/muck_profiles.rake",
    "muck-profiles.gemspec"
  ]
  s.homepage = %q{http://github.com/tatemae/muck-profiles}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Profile engine for the muck system}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<geokit>, [">= 0"])
      s.add_runtime_dependency(%q<paperclip>, [">= 0"])
      s.add_runtime_dependency(%q<sanitize>, [">= 0"])
      s.add_runtime_dependency(%q<uploader>, [">= 0"])
      s.add_runtime_dependency(%q<muck-engine>, [">= 0"])
      s.add_runtime_dependency(%q<muck-users>, [">= 0"])
      s.add_runtime_dependency(%q<muck-comments>, [">= 0"])
      s.add_runtime_dependency(%q<muck-contents>, [">= 0"])
      s.add_runtime_dependency(%q<muck-solr>, [">= 0"])
      s.add_runtime_dependency(%q<muck-shares>, [">= 0"])
      s.add_runtime_dependency(%q<muck-raker>, [">= 0"])
    else
      s.add_dependency(%q<geokit>, [">= 0"])
      s.add_dependency(%q<paperclip>, [">= 0"])
      s.add_dependency(%q<sanitize>, [">= 0"])
      s.add_dependency(%q<uploader>, [">= 0"])
      s.add_dependency(%q<muck-engine>, [">= 0"])
      s.add_dependency(%q<muck-users>, [">= 0"])
      s.add_dependency(%q<muck-comments>, [">= 0"])
      s.add_dependency(%q<muck-contents>, [">= 0"])
      s.add_dependency(%q<muck-solr>, [">= 0"])
      s.add_dependency(%q<muck-shares>, [">= 0"])
      s.add_dependency(%q<muck-raker>, [">= 0"])
    end
  else
    s.add_dependency(%q<geokit>, [">= 0"])
    s.add_dependency(%q<paperclip>, [">= 0"])
    s.add_dependency(%q<sanitize>, [">= 0"])
    s.add_dependency(%q<uploader>, [">= 0"])
    s.add_dependency(%q<muck-engine>, [">= 0"])
    s.add_dependency(%q<muck-users>, [">= 0"])
    s.add_dependency(%q<muck-comments>, [">= 0"])
    s.add_dependency(%q<muck-contents>, [">= 0"])
    s.add_dependency(%q<muck-solr>, [">= 0"])
    s.add_dependency(%q<muck-shares>, [">= 0"])
    s.add_dependency(%q<muck-raker>, [">= 0"])
  end
end

